name: Manual Nutrition Data Update

on:
  workflow_dispatch:
    inputs:
      test_mode:
        description: 'Run in test mode (pages 2-4 only)'
        required: false
        type: boolean
        default: false

jobs:
  extract-and-update:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests pdfplumber
    
    - name: Run nutrition data extraction
      run: |
        if [ "${{ inputs.test_mode }}" == "true" ]; then
          echo "Running in test mode with forced download..."
          python extract_nutrition.py --test --force
        else
          echo "Running full extraction with forced download..."
          python extract_nutrition.py --full --force
        fi
    
    - name: Check for changes
      id: check_changes
      run: |
        if [ "${{ inputs.test_mode }}" == "true" ]; then
          echo "Test mode - no commits will be made"
          echo "changes=false" >> $GITHUB_OUTPUT
        else
          git diff --quiet nutrition_data.json || echo "changes=true" >> $GITHUB_OUTPUT
        fi
    
    - name: Copy to public folder
      if: steps.check_changes.outputs.changes == 'true'
      run: |
        cp nutrition_data.json public/nutrition_data.json
    
    - name: Commit and push if changed
      if: steps.check_changes.outputs.changes == 'true'
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git add nutrition_data.json
        git add -f public/nutrition_data.json
        git commit -m "🤖 Manual update nutrition data - $(date +'%Y-%m-%d')
        
        Manually triggered extraction from Starbucks Austria PDF
        Triggered by: @${{ github.actor }}
        Source: https://www.starbucks.at/sites/starbucks-at-pwa/files/2025-04/AT%20Beverage%20Nutrition%20Summer.pdf"
        git push
    
    - name: Summary
      run: |
        if [ "${{ inputs.test_mode }}" == "true" ]; then
          echo "## Test Mode Results" >> $GITHUB_STEP_SUMMARY
          echo "Test extraction completed. Check the logs for results." >> $GITHUB_STEP_SUMMARY
          echo "No changes were committed in test mode." >> $GITHUB_STEP_SUMMARY
        elif [ "${{ steps.check_changes.outputs.changes }}" == "true" ]; then
          echo "## Update Successful ✅" >> $GITHUB_STEP_SUMMARY
          echo "Nutrition data has been updated and committed." >> $GITHUB_STEP_SUMMARY
        else
          echo "## No Changes Detected 🔄" >> $GITHUB_STEP_SUMMARY
          echo "The nutrition data is already up to date." >> $GITHUB_STEP_SUMMARY
        fi